const form = document.querySelector('#pergunta-form');
const resposta = document.querySelector('#resposta');

form.addEventListener('submit', function(event) {
	event.preventDefault();
	const pergunta = document.querySelector('#pergunta').value;
	const respostaGerada = gerarResposta(pergunta);
	exibirResposta(respostaGerada);
});

function gerarResposta(pergunta) {
	const perguntasFrequentes = {
		'O que é um buraco negro?': 'Um buraco negro é uma região do espaço-tempo onde a gravidade é tão forte que nada, nem mesmo a luz, pode escapar.',
		'Qual é a distância da Terra até a Lua?': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
		'Qual é a distância da Terra até a Lua': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
		'Qual e a distancia da terra até a lua': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
		'Qual e a distancia da terra até a lua?': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
		'Qual a distancia da terra até a lua?': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
		'Qual a distância da Terra até a Lua?':'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
		'Como é formado um eclipse solar?': 'Um eclipse solar ocorre quando a Lua passa entre a Terra e o Sol, bloqueando a luz solar e projetando uma sombra na Terra.',
		'Quantos planetas existem no Sistema Solar?': 'Existem oito planetas no Sistema Solar: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno.',
		'O que é uma estrela de nêutrons?': 'Uma estrela de nêutrons é um objeto extremamente denso e pequeno, formado a partir do colapso de uma estrela em supernova.',
		'O que é astronomia?': 'Astronomia é o estudo científico dos corpos celestes no universo, como estrelas, planetas, galáxias e objetos cósmicos.',
		'O que é um planeta?': 'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.', 
		'O que e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'o que é um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'o que e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'oq e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'Oq e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'Oq é um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'oq é um Planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'Oq é um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'o que é um planeta':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
		'Me fala sobre a tecnologia na astronomia.':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fala sobre a tecnologia na astronomia, por favor':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me conta aí sobre a tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Fala aí sobre a tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fale sobre o futuro da tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fale sobre como a tecnologia mudou a astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fale sobre as contribuições da tecnologia para a astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fale sobre o papel da tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fale sobre a importância da tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fale mais sobre a tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me dê detalhes sobre a tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me explique sobre a tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me informe sobre a tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me conte sobre a tecnologia na astronomia':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fale sobre a tecnologia na astronomia.':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',
        'Me fala sobre a tecnologia na astronomia, por favor':'A tecnologia tem sido crucial para a astronomia, permitindo-nos observar o universo em detalhes sem precedentes. O Telescópio Espacial Hubble e o Telescópio Espacial James Webb são fundamentais na detecção de galáxias distantes e exoplanetas. O Carro Espacial foi importante para o lançamento e manutenção de satélites e construção da Estação Espacial Internacional. Esses avanços tecnológicos têm permitido descobertas impressionantes sobre o universo.',






        'O que são planettas?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'Pra que servem os planetas?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'O que são planetas? Explique, por favor.':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'O que são planétas? Eles são importante?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'O que sã planetas?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'Oque são planetas?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'O que sao planetas?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'Planetas, o que isso significam?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'Quais a utilidade dos planetas?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',
        'O que sõ planetas?':'Os planetas são corpos celestes que orbitam em torno de estrelas. Eles variam em tamanho, composição e características, e são classificados em diferentes tipos, como planetas rochosos , planetas gasosos e planetas anões.',






        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'Pra que servem os sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas? Explica, por favor.': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas? Eles são importantes?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'Sistemas, o que isso significa?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'Quais a utilidade dos sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas? Eles são importante?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'Sistemas, o que isso significa?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'Quais a utilidade dos sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',
        'O que são sistemas?': 'Sistemas de estrelas são compostos por duas ou mais estrelas orbitando um centro comum. O Sistema Solar é um exemplo de sistema estelar com oito planetas orbitando o Sol. ',






        'O que são satélites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satélites artificiais?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Oq são satélites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Pra que servem os satélites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satélits?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Oque são sateletes?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satélites naturais?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Satélites, como funcionam?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Quais a utilidade dos satélites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que sõ satélites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',




        'O que são exoplanetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'O que são exo-planetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'O que é um Exoplaneta?':'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'o que é um exoplaneta?':'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'O que é um exoplaneta?':'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'O que são eckso-planetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'Oq são exoplanetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'Pra que servem os exoplanetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'O que são ezoplanetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'Oque são exoplaneetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'O que são exoplanetas, explique por favor.': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'Exoplanetas, como são descobertos?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'Quais a utilidade dos exoplanetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',
        'O que sõ exoplanetas?': 'Exoplanetas são planetas que orbitam estrelas que não o Sol. Eles são objetos astronômicos que se formam ao redor de outras estrelas, como o Sol. Os exoplanetas são muito difíceis de observar, pois são muito pequenos e estão muito distantes.',








        'O que é satelitéis?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que é satelites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que é satelitess?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que é satelitesis?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que é satelitesss?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satelites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satelitéis?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satelitess?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satelitesis?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que são satelitesss?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que é um satélite?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Quais são os tipos de satélites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Quais são as funções dos satélites?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que é um satélite natural?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'O que é um satélite artificial?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Quais são os principais satélites naturais da Terra?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',
        'Quais são os principais satélites artificiais da Terra?': 'Satélites são objetos que orbitam um corpo celeste maior, como um planeta, uma estrela ou uma galáxia. Eles podem ser naturais ou artificiais.',


        'Me fale sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fale sobre as descobertas na astronomia?': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fala sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fala sobre as descobertas na astronomia?': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fala sobre as descobertas na astronomia?': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fale sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Conte-me sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Explique-me sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Diga-me sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Apresente-me sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Fale-me sobre as descobertas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fale sobre os achados na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fale sobre os encontros na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fale sobre as invenções na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fale sobre as inovações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',
        'Me fale sobre as descobertas no espaço sideral.': 'A astronomia é uma ciência fascinante que tem sido estudada por muitos anos e tem feito importantes descobertas sobre o universo. Desde a ideia de que a Terra é redonda até a descoberta do universo em expansão e a existência de buracos negros, a astronomia tem ampliado nossa compreensão do universo e do nosso lugar nele. Nesta página, vamos explorar algumas dessas descobertas científicas e como elas impactam nossa compreensão do universo.',


        'Me fale sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as explorações na astronomia?': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fala sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fala sobre as explorações na astronomia?': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fala sobre as explorações na astronomia?': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Conte-me sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Explique-me sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Diga-me sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Apresente-me sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Fale-me sobre as explorações na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as viagens na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as expedições na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as missões na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as pesquisas na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre os estudos na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as explorações mais importantes na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as explorações mais recentes na astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',
        'Me fale sobre as explorações que mudaram a nossa compreensão da astronomia.': 'A astronomia é uma ciência fascinante que tem sido objeto de exploração há séculos. Desde o primeiro telescópio de Galileu, os avanços tecnológicos permitiram aos astrônomos estudar o universo com cada vez mais detalhes. Através de telescópios terrestres e espaciais, satélites e sondas, a astronomia nos permitiu mapear o universo visível, estudar a evolução das estrelas e das galáxias, explorar exoplanetas e procurar vida em outras partes do universo.',


        'O que são buracos negros?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'O que são buracos negros no espaço?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'O que é um buraco negro?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'O que é um buraco negro no universo?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Quais são os buracos negros?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Defina buracos negros.': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Explique buracos negros.': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Fale-me sobre buracos negros.': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Buracos negros: o que são?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Buracos negros - o que significam?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'O que são burracos negros?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'O que são buracos nergros?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Buracos escuros - o que são?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Explique a teoria dos buracos negros.': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'O que é a singularidade de um buraco negro?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Conte-me sobre a física dos buracos negros.': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Buracos negros: um mistério no espaço.': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
        'Qual é a relação entre buracos negros e estrelas?': 'Os buracos negros são regiões do espaço-tempo com uma enorme densidade, onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.',
		'O que é um buraco negro?': 'Um buraco negro é uma região do espaço-tempo onde a gravidade é tão forte que nada, nem mesmo a luz, pode escapar.',
        'Qual é a distância da Terra até a Lua?': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
        'Qual é a distância da Terra até a Lua': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
        'Qual e a distancia da terra até a lua': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
        'Qual e a distancia da terra até a lua?': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
        'Qual a distancia da terra até a lua?': 'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
        'Qual a distância da Terra até a Lua?':'A distância média entre a Terra e a Lua é de cerca de 384.400 km.',
        'Como é formado um eclipse solar?': 'Um eclipse solar ocorre quando a Lua passa entre a Terra e o Sol, bloqueando a luz solar e projetando uma sombra na Terra.',
        'Quantos planetas existem no Sistema Solar?': 'Existem oito planetas no Sistema Solar: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno.',
        'O que é uma estrela de nêutrons?': 'Uma estrela de nêutrons é um objeto extremamente denso e pequeno, formado a partir do colapso de uma estrela em supernova.',
        'O que é astronomia?': 'Astronomia é o estudo científico dos corpos celestes no universo, como estrelas, planetas, galáxias e objetos cósmicos.',
        'O que é um planeta?': 'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'O que e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'o que é um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'o que e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'oq e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'Oq e um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'Oq é um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'oq é um Planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'Oq é um planeta?':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'o que é um planeta':'Um planeta é um corpo celeste que orbita ao redor de uma estrela, possui massa suficiente para que sua própria gravidade omantenha em uma forma esférica e tenha limpado sua órbita deoutros objetos.',
        'Q que é astronomia?':'A astronomia é a ciência que estuda os corpos celestes e os fenômenos que ocorrem no universo. Ela nos ajuda a entender a origem e evolução do cosmos.',
        'Oq que é astronomia?':'A astronomia é a ciência que estuda os corpos celestes e os fenômenos que ocorrem no universo. Ela nos ajuda a entender a origem e evolução do cosmos.',
        'Q é astronomia?':'A astronomia é a ciência que estuda os corpos celestes e os fenômenos que ocorrem no universo. Ela nos ajuda a entender a origem e evolução do cosmos.',
        'Oq é astronomia?':'A astronomia é a ciência que estuda os corpos celestes e os fenômenos que ocorrem no universo. Ela nos ajuda a entender a origem e evolução do cosmos.',
        'O que estuda a astronomia?':'A astronomia é a ciência que estuda os corpos celestes e os fenômenos que ocorrem no universo. Ela nos ajuda a entender a origem e evolução do cosmos.',
        'O qe é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'Oque é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'Q é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'Oke é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O q é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'Oq é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que significa o termo "universo"?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que é o espaço sideral?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'Q é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que é o multiverso?':'O multiverso é um conceito hipotético que descreve a existência de vários universos, cada um com suas próprias leis da física e história. A ideia de que existem outros universos além do nosso é uma das mais intrigantes da ciência moderna.',
        'Qual o sentido do universo?':'A questão do sentido do universo é uma das mais antigas e complexas que a humanidade já se perguntou. Não há uma resposta única ou definitiva, e as diferentes pessoas e culturas têm suas próprias perspectivas sobre o assunto. Algumas pessoas acreditam que o universo não tem sentido, e que é simplesmente uma coleção de eventos e objetos que não têm propósito ou significado. Outros acreditam que o universo tem um propósito, e que existe algo ou alguém que o criou e o controla.',
        'O que é o universso?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O q representa o universo?':'O universo representa a infinitude, a totalidade, o mistério e a beleza. É um lugar vasto e complexo, com uma história de bilhões de anos. Ele está em constante expansão e evolução, e ainda há muito que não sabemos sobre ele.',
        'O que é o cosmos?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que é o cosmos?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que é o cosmos?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O q é esse universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que é o cosmos?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que é o cosmos?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O que é o cosmos?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'O q é o universo?':'O universo/cosmos é o conjunto de tudo o que existe, desde o microcosmo ao macrocosmo, das estrelas até as partículas subatômicas. É um sistema ordenado e harmonioso, em oposição ao caos e à desordem.',
        'o que são estrelas?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
        'o que sao estrelas?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
        'O q seria uma estrela?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
        'O q é uma estrela?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
        'Oq é uma estrela?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
        'O que é uma estrela?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
        'O que é uma estela?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
        'o que é uma estrela':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
		'o que e uma estrela':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
		'o que e uma estrela?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
		'oq é uma estrela?':'Uma estrela é uma esfera de gás quente que emite luz e calor devido a reações nucleares em seu núcleo.',
		'Qual o tamanho do planeta Terra em metros?':'O tamanho total do planeta Terra, medido porquadrado de sua superfície terrestre, é 6.39 × 10^8 m2 (cerca de 639 000 000 m2).', 
		'Qual o tamanho do Planeta Terra em metros?':'O tamanho total do planeta Terra, medido porquadrado de sua superfície terrestre, é 6.39 × 10^8 m2 (cerca de 639 000 000 m2).',
        'Qual é a diferença entre astronomia e astrologia?':'Astronomia é a ciência que estuda o universo e os corpos celestes, enquanto a astrologia é uma crença pseudocientífica que tenta relacionar as posições dos astros com a personalidade humana.',
        'Quem foi o primeiro astronauta a pisar na Lua?':'Neil Armstrong foi o primeiro astronauta a pisar na Lua em 1969, durante a missão Apollo 11.',
        ' Qual é o maior planeta do Sistema Solar?':' O maior planeta do Sistema Solar é Júpiter.',
        'Qual é o nome da galáxia onde o Sistema Solar está localizado?':' A galáxia onde o Sistema Solar está localizado é chamada de Via Láctea.',
        '':'',

	};

	if (pergunta in perguntasFrequentes) {
		return perguntasFrequentes[pergunta];
	} else {
		return 'Desculpe, não consegui entender sua pergunta. Por favor, tente novamente.';
	}
}

function exibirResposta(respostaGerada) {
	resposta.innerHTML = `
		<h2>Resposta:</h2>
		<div class="maquina-escrever">${respostaGerada}</div>
	`;
	resposta.style.display = 'block';
	const palavras = respostaGerada.split(' '); // Dividir a resposta em palavras
	console.log(respostaGerada);
	maquinaEscrever.innerText = '';
	let i = 0;
	let intervalo = setInterval(function() {
		if (i < palavras.length) {
			maquinaEscrever.innerText += palavras[i] + ' '; // Adicionar espaço entre as palavras
			i++;
		} else {
			clearInterval(intervalo);
			maquinaEscrever.classList.add('blink');
		}
	}, 50);
}